In [4]:
import sys
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
import operator
from sklearn.metrics import classification_report
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import classification_report, confusion_matrix, multilabel_confusion_matrix
from sklearn.metrics import mean_squared_error, accuracy_score, precision_score, recall_score
from sklearn.neural_network import MLPClassifier

pd.set_option('display.max_columns', None)

df = pd.read_csv("../dataset/train_processed.csv")
df = df.drop(["Payment_Behaviour"], axis=1)

X = df.drop("Credit_Score", axis=1)
y = df["Credit_Score"]
scaler = MinMaxScaler(feature_range=(0, 1))
X_rescaled = scaler.fit_transform(X)
X = pd.DataFrame(data=X_rescaled, columns=X.columns)
categories=[["Good", "Standard", "Poor"]]
encoder = OneHotEncoder(categories=categories, sparse=False)
y = encoder.fit_transform(y.values.reshape(-1, 1))

data_train, data_test, class_train, class_test = train_test_split(X, y, test_size=0.1)
mlp = MLPClassifier(solver="sgd", activation="logistic", learning_rate_init=0.3, batch_size=100, hidden_layer_sizes=(23, 17, 13), max_iter=500)
mlp.fit(data_train, class_train)
pred = mlp.predict(data_test)
print("Accuracy : ", accuracy_score(class_test, pred))
print("Mean Square Error : ", mean_squared_error(class_test, pred))

print("Confusion Matrix for each label : ")
print(multilabel_confusion_matrix(class_test, pred))

print("Classification Report : ")
print(classification_report(class_test, pred))

C:\Users\harry\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Accuracy :  0.6007604562737643
Mean Square Error :  0.242802824551874
Confusion Matrix for each label : 
[[[3068    8]
  [ 604    2]]

 [[ 783  947]
  [ 360 1592]]

 [[2258  300]
  [ 463  661]]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.20      0.00      0.01       606
           1       0.63      0.82      0.71      1952
           2       0.69      0.59      0.63      1124

   micro avg       0.64      0.61      0.63      3682
   macro avg       0.50      0.47      0.45      3682
weighted avg       0.58      0.61      0.57      3682
 samples avg       0.61      0.61      0.61      3682



C:\Users\harry\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [5]:
display(X)

Age  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
0      0.111111       0.000501               0.100349           0.001669   
1      0.111111       0.000501               0.100349           0.001669   
2      0.246914       0.005628               0.797111           0.000556   
3      0.246914       0.005628               0.797111           0.000556   
4      0.246914       0.005628               0.797111           0.000556   
...         ...            ...                    ...                ...   
36806  0.123457       0.002185               0.321314           0.002225   
36807  0.123457       0.002185               0.321314           0.002225   
36808  0.209877       0.000901               0.137593           0.003337   
36809  0.222222       0.000901               0.137593           0.003337   
36810  0.222222       0.000901               0.137593           0.003337   

       Num_Credit_Card  Interest_Rate  Num_of_Loan  Num_of_Delayed_Payment  \
0             0.002668       0.000345         0.50                0.001592   
1             0.002668       0.000345         0.50                0.001819   
2             0.003336       0.001208         0.25                0.001365   
3             0.003336       0.001208         0.25                0.001137   
4             0.003336       0.001208         0.25                0.001365   
...                ...            ...          ...                     ...   
36806         0.004670       0.001380         0.50                0.002957   
36807         0.004670       0.001380         0.50                0.002502   
36808         0.004003       0.003451         0.75                0.004776   
36809         0.004003       0.003451         0.75                0.005231   
36810         0.004003       0.003451         0.75                0.005231   

       Num_Credit_Inquiries  Outstanding_Debt  Credit_Utilization_Ratio  \
0                  0.001542          0.162051                  0.222015   
1                  0.001542          0.162051                  0.061894   
2                  0.001157          0.260719                  0.778042   
3                  0.001157          0.260719                  0.392169   
4                  0.001157          0.260719                  0.642250   
...                     ...               ...                       ...   
36806              0.001542          0.083550                  0.324417   
36807              0.001542          0.083550                  0.146579   
36808              0.003084          0.476722                  0.533864   
36809              0.003084          0.476722                  0.174938   
36810              0.003084          0.476722                  0.072310   

       Credit_History_Age  Total_EMI_per_month  Monthly_Balance  \
0                0.654229             0.000525         0.220289   
1                0.669154             0.000525         0.172384   
2                0.527363             0.002925         0.704345   
3                0.534826             0.002925         0.571699   
4                0.539801             0.002925         0.682967   
...                   ...                  ...              ...   
36806            0.855721             0.001194         0.348957   
36807            0.860697             0.001194         0.056460   
36808            0.171642             0.000922         0.147290   
36809            0.184080             0.000922         0.237044   
36810            0.186567             0.000922         0.229739   

       High_spent_Large_value_payments  High_spent_Medium_value_payments  \
0                                  0.0                               0.0   
1                                  0.0                               0.0   
2                                  0.0                               0.0   
3                                  0.0                               0.0   
4                                  0.0                               0.0   


In [6]:
display(y)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])